### ISSUE TITLE
Darter: External bootable M.2 USB enclosure is not bootable

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#10] opened 2019-09-26 01:23 UTC
On the Darter, attempting to boot from an external M.2 USB drive goes to a GRUB shell. This happens on all USB 3 type A ports on the machine. This drive works on proprietary firmware on the previous model.

**Comment by brs17** [comment] 2019-09-26 13:07
This is also the case with the same drive via USB type C.

**Comment by jackpot51** [comment] 2019-10-04 19:07
Duplicate of #23

**Closed by jackpot51** 2019-10-04 19:07 UTC
