### ISSUE TITLE
will lemp11 be getting a firmware update

### ISSUE THREAD

**Issue by JordanBoulan** [system76/firmware-open#420] opened 2023-05-24 19:24 UTC
I just got my lemp11 a few months ago. It still doesn't support s3 sleep which is very frustrating.
Secure boot would be a nice feature for windows 11 eventually as well. 
I see in the changelog s3 has been fixed and secure boot has been added.

So just want to know if the lemp11 will eventually get an update with s3 sleep and secure boot support because I don't see a reason it couldn't support those features. 

EDIT: I see in models lemp11 got updated to support secure boot. So maybe it just has not been released yet? An official release would be nice. I would rather not have to build and flash it myself.

Thanks.

**Comment by leviport** [comment] 2023-05-24 19:45
As you say, it has been added in this repo. Official releases are built from this repo and extensively QA tested to make sure nothing bad will happen when the new firmware is released into the wild. Building and flashing from this repo yourself is doable, but there are no guarantees that there will be no regressions or negative behavior since it hasn't had the same test coverage. 

We are planning another official release for lemp11, but we don't currently have a timeline on that. Hopefully we can get to it soon.

**Comment by crawfxrd** [comment] 2023-05-31 19:24
Most boards have updates to 2023-05-25_5608a8d staged and need to be approved before release.

**Closed by crawfxrd** 2023-05-31 19:24 UTC
Labels: question
