### ISSUE TITLE
Support disabling firmware USB stack, while allowing the OS to use USB devices

### ISSUE THREAD

**Issue by DemiMarie** [system76/firmware-open#561] opened 2024-07-03 05:16 UTC
Qubes OS isolates USB devices in a dedicated virtual machine.  This prevents a malicious USB device from compromising the entire system.  However, this protection fails if USB keyboards and mice are supported in the firmware, because a malicious device can inject keystrokes into GRUB or trigger system recovery.

To prevent this attack, firmware could have a configuration option to ignore all attached USB devices.  This blocks the above attack: the malicious device will be ignored by firmware, and Qubes OS limits the damage the device can do.

**Comment by crawfxrd** [comment] 2024-12-19 23:57
Duplicate of #589

**Closed by crawfxrd** 2024-12-19 23:57 UTC
Labels: priority:low
