### ISSUE TITLE
Setting a password for the UEFI BIOS

### ISSUE THREAD

**Issue by JoonasC** [system76/firmware-open#254] opened 2021-10-02 20:45 UTC
I'm currently using an Oryp6 and there doesn't seem to be an option to set a password for the UEFI BIOS setup screen. Not sure if this is a feature that coreboot is lacking, or something that you guys can implement, but it'd be nice to have. The lack of a password makes it easy to install a new os without authorization for example.

**Comment by crawfxrd** [comment] 2021-10-03 00:32
Duplicate of #174

**Closed by crawfxrd** 2021-10-03 00:32 UTC
