### ISSUE TITLE
Oryp8 ME Disable

### ISSUE THREAD

**Issue by Localacct21** [system76/firmware-open#266] opened 2021-12-19 02:22 UTC
Will I be able to disable ME in the near future with a Oryp8?

**Comment by crawfxrd** [comment] 2021-12-19 02:28
It's already disabled.

**Comment by Localacct21** [comment] 2021-12-19 02:48
No its not. https://user-images.githubusercontent.com/78702586/146661876-60634f82-da45-4fdf-bbab-76b9b076328b.mp4

**Comment by crawfxrd** [comment] 2021-12-19 06:41
Oh, right. It wasn't released.

It will be disabled by default when #260 is released, but I'm closing this as a duplicate of #197.

**Closed by crawfxrd** 2021-12-19 06:41 UTC

**Comment by crawfxrd** [comment] 2022-09-12 16:19
Released with 2022-09-07_74e75ff.
