### ISSUE TITLE
After updating firmware, system boots into BIOS Menu

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#34] opened 2019-10-07 15:41 UTC
After a firmware update on open firmware, the system boots into the BIOS menu. This was done with proprietary firmware to disable the M.E. As this is not necessary on models using open firmware, there is no need to boot into the BIOS.

**Comment by jackpot51** [comment] 2019-10-07 19:13
Duplicate of #31

**Closed by jackpot51** 2019-10-07 19:13 UTC
