### ISSUE TITLE
scripts/install-deps.sh fails 

### ISSUE THREAD

**Issue by randomuygvruyv65423654** [system76/firmware-open#514] opened 2024-02-13 17:54 UTC
- Model: 
- BIOS version: 
- EC version: 
- OS:  Debian 12
- Kernel:  6.1.0-17-amd64

There is no package with the name devmem2 in Debian 12
If I comment out all the apt lines and run apt install manually the script still fails. If I run git lfs pull && git submodule update --init --recursive --checkout --progress manually the both run with no problem. It only fails in the script.

### Steps to reproduce

git clone https://github.com/system76/firmware-open
cd firmware-open
scripts/install-deps.sh

### Expected behavior
packages should install and git submodules should checkout

### Actual behavior

E: Unable to locate package devmem2

Or if commented out apt install lines

Reading package lists...
Installing GIT LFS hooks
Git LFS initialized.
Downloading GIT LFS artifacts
Not in a Git repository.
Failed to install dependencies!

**Comment by crawfxrd** [comment] 2024-02-21 02:59
Duplicate of #265.

LFS issue is likely caused by a previous failure.

**Closed** 2024-02-21 16:38 UTC
