### ISSUE TITLE
Unable to boot from Micro SD

### ISSUE THREAD

**Issue by pr0xidian** [system76/firmware-open#209] opened 2021-05-18 19:50 UTC
Good afternoon! I reached out to System76 support to see if it was possible to boot from Micro SD (I have an oryx pro 6 oryp6 with coreboot) as I can't seem to do a micro SD boot. Is this something that could be enabled? It would be a very useful feature for me. 

Best Regards, -Seth Forbus

**Comment by crawfxrd** [comment] 2021-05-18 19:55
Duplicate of #63

**Closed by crawfxrd** 2021-05-18 19:55 UTC
