### ISSUE TITLE
Provide and document firmware rollback solution

### ISSUE THREAD

**Issue by curiousercreative** [system76/firmware-open#289] opened 2022-01-31 14:04 UTC
Given regressions will be introduced in firmware updates, users should have the ability to rollback a firmware update and/or self-serve flashing an arbitrary firmware release for their machine. However it is implemented, flashable firmware organized by supported device and sorted by release date should be available. Yes the source to build the firmware is available here, but I've personally failed to build firmware releases from 6+ months ago on the current Pop!_OS release (likely due to dependencies).

Relates to:
- https://github.com/system76/firmware-open/issues/99
- https://github.com/system76/firmware-open/issues/282#issuecomment-1016626105

**Comment by jackpot51** [comment] 2022-01-31 15:03
We intend to use LVFS at some point which will introduce this capability

**Comment by jacobgkau** [comment] 2022-01-31 15:20
This seems like a duplicate of https://github.com/system76/firmware-open/issues/99. That issue is requesting a rollback feature and this issue is requesting a rollback feature.

**Comment by curiousercreative** [comment] 2022-01-31 15:41
@jacobgkau it mostly duplicates, I agree.

**Comment by jacobgkau** [comment] 2022-01-31 15:51
Thanks. I'm going to close this as a duplicate of https://github.com/system76/firmware-open/issues/99 to keep things organized, but we are interested in making this easier/more accessible, both from a documentation and tooling perspective.

**Closed by jacobgkau** 2022-01-31 15:51 UTC
