### ISSUE TITLE
lemp10 (& galp5) Boot from Micro SD Card

### ISSUE THREAD

**Issue by Dygear** [system76/firmware-open#179] opened 2021-03-17 18:36 UTC
Would it be possible to add an option to boot from the Micro SD Card slot? I do know that it would be very slow compared to a USB drive in most cases, or indeed the onboard NVMe drives, but I would like the option. I run Raspberry Pi OS on the dozen plus computers around here and from time to time I need to be in that OS for a sanity check of the environment. Having a boot from Micro SD Card would be a nice option.

**Comment by crawfxrd** [comment] 2021-03-17 18:39
Duplicate of #63

**Closed by crawfxrd** 2021-03-17 18:39 UTC

**Comment by Dygear** [comment] 2021-03-17 18:49
Ah, I searched for lemp10 and SD Card and nothing came up. I really should of made my search more board. Sorry.
